### ISSUE TITLE
Provence-Alpes-Côte_d'Azur, FR getting old ISO 3166-2 code

### ISSUE THREAD

**Issue by nickpeihl** [nyurik/scripted-regions#1]
Wikidata has defined the [end time ](https://www.wikidata.org/wiki/Q15104#identifiers) for the deprecated ISO3166-2 code (FR-U) for Provence-Alpes-Côte_d'Azur (FR-PAC) region in France. The [France regions query](https://sophox.org/sophox/#%0A%23defaultView%3AMapRegions%0A%23%20version%208%0ASELECT%0A%20%20%28if%28bound%28%3Fid2%29%2C%3Fid2%2C%3Fid%29%20as%20%3Fid%29%0A%20%20%3Fiso_3166_2%20%3Flabel_en%20%3Flabel_fr%0AWHERE%20%7B%0A%23%20Using%20nested%20query%20to%20ensure%20there%20is%20only%20one%20%3Fid2%20value%0A%7BSELECT%0A%20%20%3Fid%0A%20%20%28SAMPLE%28%3Fid2%29%20as%20%3Fid2%29%0A%20%20%28SAMPLE%28%3Fiso_3166_2%29%20as%20%3Fiso_3166_2%29%0A%20%20%28SAMPLE%28%3Flabel_en%29%20as%20%3Flabel_en%29%0A%20%20%28SAMPLE%28%3Flabel_fr%29%20as%20%3Flabel_fr%29%0AWHERE%20%7B%0A%20%20%23%20List%20of%20regions%2C%20whose%20sub-regions%20we%20want.%0A%20%20VALUES%20%3Fentity%20%7B%20wd%3AQ142%20%7D%0A%0A%20%20%23%20P150%20%3D%20%22contains%20administrative%20territorial%20entity%22%0A%20%20%3Fentity%20wdt%3AP150%20%3Fid%20.%0A%0A%0A%0A%20%20OPTIONAL%20%7B%20%3Fid%20rdfs%3Alabel%20%3Flabel_en%20.%20FILTER%28LANG%28%3Flabel_en%29%20%3D%20%22en%22%29%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fid%20rdfs%3Alabel%20%3Flabel_fr%20.%20FILTER%28LANG%28%3Flabel_fr%29%20%3D%20%22fr%22%29%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fid%20wdt%3AP300%20%3Fiso_3166_2%20%7D%0A%7D%0A%23%20remove%20possible%20ID%20duplicates%0AGROUP%20BY%20%3Fid%7D%0A%7D%0A) does not check for the existence of the end time so it assigns the wrong code when generating the geojson and topojson files.

I spent a while looking at this, but my SPARQL experience is lacking and I'm not sure how to fix it.

**Comment by nyurik** [comment]
@nickpeihl there is a much easier fix ([already done](https://www.wikidata.org/w/index.php?title=Q15104&type=revision&diff=658453021&oldid=658083263)) -- Wikidata has a concept of "rank" (shown as up/down arrows next to each value).  By default its "normal" rank, but if some values are currently accurate, while other values were accurate in the past (e.g. have endtime attribute), the ones that are still accurate should have a "preferred" rank.  What this does is that the `wdt:...` values (otherwise called "wikidata truthy values" - we use them as `wdt:P300`) in Wikidata Query Service and Sophox will be set to just the preferred ones, ignoring all the "normal" ones.
